include::../includes/attributes.adoc[]
= Implementing a Diameter Service
Diameter implementations are exposed as CDI beans are automatically registered and started

To implement a service a class needs to be defined and annotated with `@DiameterService` and `@DiameterServiceOptions`.
If `@DiameterServiceOption` is not specified the default config profile will be used.
Only one Diameter service combination of application type and mode can be defined at any given time.
For example only one CAA / Server service can be defined and a `DiameterConfigException` will be generated if additional one is defined.
It is however allowed to define additional Diameter Services for other Application Type and mode combination on the same Diameter stack, but not in the same service.

TIP: For clarity, it is perfectly legal to to have two Diameter Services, one for CAA / Client and another for CAA / Server, or any other combination of application type and mode as long as there is only one per service per diameter stack.

The DiameterService interceptor will initialise all the configured applications and *start* the Diameter stack (if not already started).
In addition to registering the session factories it will also register a Network Listener for each

== Example

[source,java]
----
@DiameterService <1>
@DiameterServiceOption(config = "client1") <2>
public class MyDiameterService implements ClientCCASessionListener <3>
{
	@Override
	public void doCreditControlAnswer(ClientCCASession session, JCreditControlRequest request, JCreditControlAnswer answer) throws InternalException
	{
	    //...
	}
}
----

<1> Marking the class as a diameter service
<2> The optional configuration option to apply to the diameter service.
If not define the <default> configuration will be used.
<3> Implements the the SessionListener associated with the `Session Type`.
(See List below)

== Diameter Server mode

When the diameter stack is started in SERVER mode, the Diameter Service interceptor automatically creates a network listener for defined Diameter Service.
The interceptor will skip creating a listener if it detects that the Diameter Service has implemented the `NetworkListener` interface.

TIP: In most cases you do not need to implement your own `NetworkListener` and you can let the interceptor create one for you!

== Injecting the Diameter stack

An application can inject the diameter stack and configuration for a given configuration profile.

NOTE: Only one stack is created per enabled configuration profile.

TIP: The stack will only be active if there is a defined DiameterService for the stack.

[source,java]
----

@ApplicationScoped public class Demo
{
    @DiameterConfig <1>
    Stack stack;

    @DiameterConfig("test2") <2>
    Configuration test2Config;

    //...
}
----

<1> Injecting the Diameter stack associated with the "<default>" configuration.
<2> Injecting the Diameter configuration for the "test2" configuration.

== Application Session Types

.Supported Application Session type.
|===
| *Session Type* | *Server Session Interface* | *Client Session Interface*
| Credit Control Application (CCA) | ServerCCASessionListener | ClientCCASessionListener
| Rx |  ClientRxSessionListener | ClientRxSessionListener
| S6a |  ServerS6aSessionListener | ClientS6aSessionListener
| Gq | ServerAuthSessionListener | ClientAuthSessionListener
|===

== Using TLS

== Example Configuration

The example configuration defines two sets of client diameter config.
One is the default config and the other is named config called 'test1'.

[source,properties]
----
diameter.local-peer.uri=aaa://ocsclient:1812
diameter.local-peer.ip-addresses=0.0.0.0, 127.0.0.1
diameter.local-peer.realm=server.test.com
diameter.local-peer.product-name=Diameter Test Client
diameter.local-peer.firmware-revision=1
diameter.local-peer.applications.0.auth-appl-id=4
diameter.local-peer.applications.1.auth-appl-id=4
diameter.local-peer.applications.1.vendor-id=10415
diameter.parameter.use-virtual-threads=true
diameter.network.peers.peer-uri=aaa://ocs.test.org:3868
diameter.network.peers.ip=127.0.0.1
diameter.network.peers.attempt-connect=true
diameter.network.peers.rating=0
diameter.network.realms.realm-name=server.test.com
diameter.network.realms.peers=192.168.241.1,localhost
diameter.network.realms.local-action=local
diameter.network.realms.dynamic=false
diameter.network.realms.exp-time=1
diameter.network.realms.application-id.auth-appl-id=4

diameter.test1.local-peer.uri=aaa://ocsclient:1813
diameter.test1.local-peer.ip-addresses[0]=0.0.0.0, 127.0.0.1
diameter.test1.local-peer.realm=server.test.com
diameter.test1.local-peer.product-name=Diameter Test Client
diameter.test1.local-peer.firmware-revision=1
diameter.test1.local-peer.applications.0.auth-appl-id=4
diameter.test1.local-peer.applications.1.auth-appl-id=4
diameter.test1.local-peer.applications.1.vendor-id=10415
diameter.test1.parameter.use-virtual-threads=true
diameter.test1.network.peers.peer-uri=aaa://ocs.test.org:3868
diameter.test1.network.peers.ip=127.0.0.1
diameter.test1.network.peers.attempt-connect=true
diameter.test1.network.peers.rating=0
diameter.test1.network.realms.realm-name=server.test.com
diameter.test1.network.realms.peers=192.168.241.1,localhost
diameter.test1.network.realms.local-action=local
diameter.test1.network.realms.dynamic=false
diameter.test1.network.realms.exp-time=1
diameter.test1.network.realms.application-id.auth-appl-id=4
----

TIP:For more information about the extension configuration please refer to the <<configuration-reference,Configuration Reference>>.

[[configuration-reference]]
include::../includes/quarkus-diameter.adoc[leveloffset=+1]
