include::../includes/attributes.adoc[]
= Implementing a Diameter Service
Diameter implementations are exposed as CDI beans are automatically registered and started

To implement a service a class needs to be defined and annotated with `@DiameterService` and `@DiameterServiceOptions`.
The `@DiameterServiceOption` is required and if missing a build time exception will be generated.
The DiameterServiceOption is used to define the application type to setup.
Only one Diameter service combination of application type and mode can be defined at any given time.
For example only one CAA / Server service can be defined and a `DiameterConfigException` will be generated if additional one is defined.
It is however allowed to define additional Diameter Services for other Application Type and mode combination on the same stack.

TIP: For clarity, it is perfectly legal to to have two Diameter Services one for CAA / Client and another for CAA / Server, or any other combination of application type and mode as long as there is only one per combination per diameter stack.

The DiameterService interceptor will initialise all the configured applications and *start* the Diameter stack (if not already started).
In addition to registering the session factories it will also register a Network Listener for each

=== Example

[source,java]
----
@DiameterService <1>
@DiameterServiceOption( <2>
		mode = ApplicationMode.CLIENT, <3>
		type = DiameterApplication.CCA, <4>
		config = "client1" <5>
)
public class MyDiameterService implements ClientCCASessionListener <6>
{
	@Override
	public void doCreditControlAnswer(ClientCCASession session, JCreditControlRequest request, JCreditControlAnswer answer) throws InternalException
	{
	    //...
	}
}
----

<1> Marking the class as a diameter service
<2> The option to apply to the diameter service
<3> The mode of the service (CLIENT or SERVER)
<4> The application session type (see list below)
<5> The configuration profile the use
<6> Implements the the SessionListener associated with the `Session Type`.
(See List below)

NOTE: If the SessionListener associated with the Session Type is not implemented an exception will be generated at startup.

== Diameter Server mode

When the diameter stack is started in SERVER mode, the Diameter Service interceptor automatically creates a network listener for defined Diameter Service.
The interceptor will skip creating a listener if it detects that the Diameter Service has implemented the `NetworkListener` interface.

TIP: In most cases you do not need to implement your own `NetworkListener` and you can let the interceptor create one for you!

== Injecting the Diameter stack

An application can inject the diameter stack and configuration for a given configuration profile.

NOTE: Only one stack is created per enabled configuration profile.

TIP: The stack will only be active if there is a defined DiameterService for the stack.

[source,java]
----

@ApplicationScoped public class Demo
{
@DiameterConfig("test1")<1> Stack stack;

    @DiameterConfig("test2")<2>
    Configuration test2Config;

    //...
}
----

<1> Injecting the Diameter stack associated with the "test1" configuration.
<2> Injecting the Diameter configuration for the "test2" configuration.

== Application Session Types

.Supported Application Session type.
|===
| *Session Type* | *Server Session Interface* | *Client Session Interface*
| Credit Control Application (CCA) | ServerCCASessionListener | ClientCCASessionListener
| Rx |  ClientRxSessionListener | ClientRxSessionListener
| S6a |  ServerS6aSessionListener | ClientS6aSessionListener
| Gq | ServerAuthSessionListener | ClientAuthSessionListener
|===

== Example Configuration

The example configuration defines two sets of client diameter config.
One is the default config and the other is named config called 'test1'.

[source,properties]
----
diameter.local-peer.uri=aaa://ocsclient:1812
diameter.local-peer.ip-addresses[0]=0.0.0.0
diameter.local-peer.ip-addresses[1]=127.0.0.1
diameter.local-peer.realm=server.test.com
diameter.local-peer.product-name=Diameter Test Client
diameter.local-peer.firmware-revision=1
diameter.local-peer.applications[0].auth-appl-id=4
diameter.local-peer.applications[1].auth-appl-id=4
diameter.local-peer.applications[1].vendor-id=10415
diameter.parameter.use-virtual-threads=true
diameter.network.peers[0].peer-uri=aaa://ocs.test.org:3868
diameter.network.peers[0].ip=127.0.0.1
diameter.network.peers[0].attempt-connect=true
diameter.network.peers[0].rating=0
diameter.network.realms[0].realm-name=server.test.com
diameter.network.realms[0].peers=192.168.241.1,localhost
diameter.network.realms[0].local-action=local
diameter.network.realms[0].dynamic=false
diameter.network.realms[0].exp-time=1
diameter.network.realms[0].application-id.auth-appl-id=4

diameter.test1.local-peer.uri=aaa://ocsclient:1813
diameter.test1.local-peer.ip-addresses[0]=0.0.0.0
diameter.test1.local-peer.ip-addresses[1]=127.0.0.1
diameter.test1.local-peer.realm=server.test.com
diameter.test1.local-peer.product-name=Diameter Test Client
diameter.test1.local-peer.firmware-revision=1
diameter.test1.local-peer.applications[0].auth-appl-id=4
diameter.test1.local-peer.applications[1].auth-appl-id=4
diameter.test1.local-peer.applications[1].vendor-id=10415
diameter.test1.parameter.use-virtual-threads=true
diameter.test1.network.peers[0].peer-uri=aaa://ocs.test.org:3868
diameter.test1.network.peers[0].ip=127.0.0.1
diameter.test1.network.peers[0].attempt-connect=true
diameter.test1.network.peers[0].rating=0
diameter.test1.network.realms[0].realm-name=server.test.com
diameter.test1.network.realms[0].peers=192.168.241.1,localhost
diameter.test1.network.realms[0].local-action=local
diameter.test1.network.realms[0].dynamic=false
diameter.test1.network.realms[0].exp-time=1
diameter.test1.network.realms[0].application-id.auth-appl-id=4
----

TIP:For more information about the extension configuration please refer to the <<configuration-reference,Configuration Reference>>.

[[configuration-reference]]
== Configuration Reference

include::../includes/diameter.adoc[leveloffset=+1]
